displayRpcPort: 5000

# Which tab to show if a button is pressed
# Or empty if the button should be ignored.
button0Tab: "tab0"
button1Tab: "tab1"
button2Tab: "tab2"

# If a startupMessage is set, then this message
# is shown on the default tab on startup, and cleared on first write.
startupMessage: "Starting up..."

# If a defaultTab and returnToDefaultAfterXSeconds is set,
# then it will automatically show that tab if no button is pressed
# in X seconds.
defaultTab: "tab0"
returnToDefaultAfterXSeconds: 30

# If true, all display calls are logged to console,
# even if there is a real display connected.
# Note that if no display is connected, then all calls are logged to the console anyway
logCalls: false


# If true, the full contents of the display will be shown on the console
# whenever the display contents are changed.
# ---------------------------
# |           |             |
# | Like this |             |
# |           |             |
# ---------------------------
#
# If there is content on multiple tabs, they are shown side by side like above.
simulateDisplayOnConsole: true