displayRpcPort: 5000

# Which tab to show if a button is pressed
# Or empty if the button should be ignored.
button0Tab: "default"
button1Tab: "tab1"
button2Tab: "tab2"

# If a startupMessage is set, then this message
# is shown on the default tab on startup, and cleared on first write.
startupMessage: "Starting up..."

# If a defaultTab and returnToDefaultAfterXSeconds is set,
# then it will automatically show that tab if no button is pressed
# in X seconds.
defaultTab: "default"
returnToDefaultAfterXSeconds: 30

# If true, all display calls are logged to console,
# even if there is a real display connected.
# Note that if no display is connected, then all calls are logged to the console anyway
logCalls: false